mysite/account/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.SignUp, name='signup'),
    # path('password_change/', views.change_password, name='change-password'),
    path('activate/<uidb64>/<token>', views.Activate, name='activate')
]

mysite/apps/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
	path('', TemplateView.as_view(template_name='welcome.html'), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('forum/', include('forums.urls', namespace='forums-path'))
]

mysite/forums/urls.py
from django.urls import path
from .views import (ForumCreate, ForumListView, ForumUserListView, 
				   ForumDetailView, ForumUpdateView, ForumDeleteView,
				   CommentCreateView, CommentUpdateView, CommentDeleteView)

## Namespace
app_name = 'forums-path'

urlpatterns = [
	path('', ForumListView.as_view(), name='forum-list'),
	path('add/', ForumCreate.as_view(), name='forum-add'),
	path('edit/<int:pk>', ForumUpdateView.as_view(), name='forum-edit'),
	path('delete/<int:pk>', ForumDeleteView.as_view(), name='forum-delete'),
	path('<slug:slug>/', ForumDetailView.as_view(), name='forum-detail'),
	path('by/<username>/', ForumUserListView.as_view(), name='forum-by'),
	path('add-comment/<int:pk>', CommentCreateView.as_view(), name='add-comment'),
	path('edit-comment/<int:pk>', CommentUpdateView.as_view(), name='edit-comment'),
	path('delete-comment/<int:pk>', CommentDeleteView.as_view(), name='delete-comment'),
]

mysite/account/models.py
from django.db import models

# Create your models here.

mysite/forums/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
import time

class Forum(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	title = models.CharField(max_length=100)
	slug = models.SlugField(unique=True)
	desc = models.TextField()
	created_at = models.DateTimeField(auto_now_add=True)

	def save(self, *args, **kwargs):
		if self.pk is None:
			self.slug = slugify(self.title) + '-' + time.strftime("%Y%m%d%H%M%S")
		super(Forum, self).save(*args, **kwargs)

	def __str__(self):
		return self.title

class Comment(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	forum = models.ForeignKey(Forum, on_delete=models.CASCADE)
	desc = models.TextField()
	created_at = models.DateTimeField(auto_now_add=True)

	def get_absolute_url(self):
		return reverse('forum-list')

class Profile(models.Model):
	user 	= models.OneToOneField(User, on_delete=models.CASCADE)
	activation_key 	= models.CharField(max_length=255, default=1)
	email_validated = models.BooleanField(default=False)

	def __str__(self):
		return self.user.username

@receiver(post_save, sender=User, dispatch_uid="save_new_user_profile")
def save_profile(sender, instance, created, **kwargs):
	user = instance
	if created:
		profile = Profile(user=user)
		profile.save()

mysite/account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
	email = forms.EmailField(max_length=200, help_text='Required')

	class Meta:
		model = User
		fields = ('username', 'email', 'password1', 'password2')
 

mysite/forums/forms.py
from django import forms


class CommentForm(forms.Form):
    desc = forms.CharField(widget=forms.Textarea)

mysite/account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.contrib import messages
from .forms import SignUpForm
from .token import account_activation_token
from django.contrib.auth.models import User
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.sites.shortcuts import get_current_site

def SignUp(request):
	if request.method == 'POST':
		form = SignUpForm(request.POST)
		if form.is_valid():
			user  = form.save()
			user.is_active = False
			user.save()
			token = account_activation_token.make_token(user)
			# Send email
			subject = "Activate your account from email"

			message = render_to_string('activation_email.html',{
					'user' : user,
					'domain' : get_current_site(request).domain,
					'uid' : urlsafe_base64_encode(force_bytes(user.pk)).decode(),
					'token' : token
				}
			)
			user.email_user(subject, message)
			return redirect(reverse('home'))
	else:
		form = SignUpForm()

	return render(request, 'signup.html', {'signupForm' : form})

# def ChangePassword(request):
# 	if request.method == 'POST':
# 		form = PasswordChangeForm(request.user, request.POST)
# 		if form.is_valid():
# 			user = form.save()
# 			update_session_auth_hash(request, user)
# 			return redirect(reverse('home'))
# 	else:
# 		form = PasswordChangeForm(request.user)
# 	return render(request, 'change_password.html', {'form' : form})
## OLD password: newadmin1994
## New password: admin1994

def Activate(request, uidb64, token):
	uid = force_text(urlsafe_base64_decode(uidb64).decode())
	user = User.objects.get(pk=uid)

	if user is not None and account_activation_token.check_token(user, token):
		user.is_active = True
		user.profile.email_validated = True
		user.save()
		return redirect(reverse('home'))

mysite/forums/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from .models import Forum, Comment
from .forms import CommentForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import HttpResponseForbidden
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy

@method_decorator(login_required, name='dispatch')
class ForumListView(ListView):
	model = Forum
	queryset = Forum.objects.order_by('-created_at')
	paginate_by = 2

class ForumUserListView(ListView):
	template_name = 'forums/forum_by_user.html'
	def get_queryset(self):
		self.user = get_object_or_404(User, username = self.kwargs['username'])
		return Forum.objects.filter(user = self.user)

class ForumDetailView(DetailView):
	model = Forum
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['form_comment'] = CommentForm()
		return context

class OwnerProtectMixin(object):
	def dispatch(self, request, *args, **kwargs):
		objectUser = self.get_object()
		if objectUser.user != self.request.user:
			return HttpResponseForbidden()
		return super(OwnerProtectMixin, self).dispatch(request, *args, **kwargs)


@method_decorator(login_required, name='dispatch')
class ForumUpdateView(OwnerProtectMixin, UpdateView):
	model = Forum
	fields = ['title','desc']
	template_name = 'forums/forum_update_form.html'

	def get_success_url(self, **kwargs):
		return reverse_lazy('forum-detail', kwargs={'slug' : self.object.slug})


@method_decorator(login_required, name='dispatch')
class ForumDeleteView(SuccessMessageMixin, OwnerProtectMixin, DeleteView):
	model = Forum
	success_url = '/forum'
	success_message = 'Forum was successfully deleted'

@method_decorator(login_required, name='dispatch')
class ForumCreate(SuccessMessageMixin, CreateView):
	model = Forum
	fields = ['title','desc']

	def form_valid(self, form):
		form.instance.user = self.request.user
		return super().form_valid(form)

class CommentCreateView(CreateView):
	model = Comment
	fields = ['desc']
	success_message = 'Forum was successfully created'

	def form_valid(self, form):
		_forum = get_object_or_404(Forum, id=self.kwargs['pk'])
		form.instance.user = self.request.user
		form.instance.forum = _forum
		return super().form_valid(form)

@method_decorator(login_required, name='dispatch')
class CommentUpdateView(OwnerProtectMixin, UpdateView):
	model = Comment
	fields = ['desc']
	template_name = 'forums/forum_update_comment.html'

@method_decorator(login_required, name='dispatch')
class CommentDeleteView(OwnerProtectMixin, DeleteView):
	model = Comment
	success_url = '/forum'

mysite/account/templates/activation_email.html
{% autoescape off %}
	Hi, {{user.username}}
	Please click the link below, to activate your account
	http://{{domain}}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

mysite/account/templates/change_password.html
{% extends "base.html" %}

{% block title %} Change Password{% endblock %}

{% block content %}
<h2>Change your password</h2>
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit" name="button">Submit</button>
</form>

{% endblock%}

mysite/account/templates/signup.html
{% extends "base.html" %}

{% block title %} Sign Up{% endblock %}

{% block content %}
<h2>Sign Up</h2>
<form method="post">
	{% csrf_token %}
	<p>Token : {{token}}</p>
	{{ signupForm.as_p }}
	<button type="submit" name="button">Register</button>
</form>

{% endblock%}

mysite/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"  integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-primary navbar-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	<ul class="navbar-nav mr-auto">
	      <li class="nav-item active">
	        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
	      </li>
		{% if user.is_authenticated %}
	      <li class="nav-item">
	      	<a class="nav-link" href="{% url 'logout' %}">Logout</a>
	      </li>
	     <li class="nav-item">
	      	<a class="nav-link" href="#">{{user}}</a>
	      </li>
	    {% else %}
	      <li class="nav-item">
	        <a class="nav-link" href="{% url 'signup' %}">Register</a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="{% url 'login' %}">Login</a>
	      </li>
	    {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
    <!-- start display message -->
 	{% if messages %}
 	<div class="card bg-success text-white">
    	{% for message in messages %}
      		<div class="card-body">Forum was successfully created</div>
      	{% endfor %}
  	</div>
    {% endif %}
    {% block content %}
    {% endblock %}
</body>
</html>

mysite/templates/forums/forum_detail.html
{% extends "base.html" %}

{% load humanize %}

{% block title %} {{object.title}} {% endblock %}

{% block content %}
<div class="jumbotron">
  <h1>{{object.title}}</h1>
  {% if request.user == object.user %}
  <a href="{% url 'forum-edit' object.id %}">Edit</a>
  <form method="post" action="{% url 'forum-delete' object.id %}">
  	{% csrf_token %} <input type="submit" value="Delete">
  </form>
  {% endif  %}
  <p style="font-size: 20px;">{{ object.desc }}</p>
  - <span><i>{{object.created_at | naturaltime}}</i></span>
  <hr>
	<!-- Display comment -->
  {% for comment in object.comment_set.all %}
  	<p>
  		{{comment.desc}}
	  	{% if request.user == comment.user %}
	  		<a href="{% url 'edit-comment' comment.id %}">Edit</a>
	  		<form method="post" action="{% url 'delete-comment' comment.id %}">
	  			{% csrf_token %}
	  			<button class="btn btn-danger" type="submit">Delete</button>
	  		</form>
	  	{% endif %}
		<br><span style="font-size: 12px;"><i>by {{comment.user}}</i></span>
  	</p>
  {% endfor %}

	<form method="post" action="{% url 'add-comment' object.id %}">
	  	{% csrf_token %}
	  	{{ form_comment }}
	  	<input type="submit" name="Add Comment">
	</form>
</div>
{% endblock %}

mysite/templates/forums/forum_form.html
{% extends "base.html" %}

{% block title %} Create Forums{% endblock %}

{% block content %}
<h2>Add Forum</h2>
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit" name="button">Submit</button>
</form>

{% endblock%}

mysite/templates/forums/forum_list.html
{% extends "base.html" %}

{% load humanize %}

{% block title %} List Forum{% endblock %}

{% block content %}
{% if messages %}
<div class="card bg-danger text-white">
	{% for message in messages %}
		<div class="card-body">Forum was successfully created</div>
	{% endfor %}
</div>
{% endif %}
<div class="jumbotron">
  <h1>Forums</h1> 
 	<ul>
 		{% for forum in object_list %}
 			<li><a href="{% url 'forums-path:forum-detail' forum.slug %}"><b>{{forum.title}}</b></a> | <a href="{% url 'forums-path:forum-by' forum.user %}">{{forum.user}}</a> | <span style="font-size: 12px;"><i>{{forum.created_at | naturaltime}}</i></span></li><br>
 		{% endfor %}
 	</ul>
 	{% include 'snippets/pagination.html' %}
</div>
{% endblock%}

mysite/templates/forums/forum_update_comment.html
{% extends "base.html" %}

{% block title %} Edit Comment {% endblock %}

{% block content %}
<h2>Edit Comment</h2>
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit" name="button">Submit</button>
</form>

{% endblock%}

mysite/templates/forums/forum_update_form.html
{% extends "base.html" %}

{% block title %} Edit Forum {% endblock %}

{% block content %}
<h2>Edit Forum</h2>
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit" name="button">Submit</button>
</form>

{% endblock%}

mysite/templates/snippets/pagination.html
{% if is_paginated %}
  <nav>
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li>
          <a href="?page={{ page_obj.previous_page_number }}">
            <span>Previous</span>
          </a>
        </li>
      {% else %}
        <li class="disabled">
          <a href="#">
            <span>Previous</span>
          </a>
        </li>
      {% endif %}

      {% for page in paginator.page_range %}
        <li {% if page == page_obj.number %}class="active"{% endif %}>
          <a href="?page={{ page }}">{{ page }}</a>
        </li>
      {% endfor %}

      {% if page_obj.has_next %}
        <li>
          <a href="?page={{ page_obj.next_page_number }}">
            <span>Next</span>
          </a>
        </li>
      {% else %}
        <li {% if not page_obj.has_next %}class="disabled"{% endif %}>
          <a href="#">
            <span>Next</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

mysite/templates/welcome.html
{% extends "base.html" %}

{% block title %} Sign in{% endblock %}

{% block content %}
<div class="jumbotron">
  <h1>Forum Apps</h1> 
  <p>Welcome to landing page</p> 
</div>
{% endblock%}